# Builds Python wheels (including stubs) and creates a draft release
name: Build Python release

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022]
        python-version: [3.12, 3.13]

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
            CIBW_BEFORE_BUILD_LINUX: "python3 -m pip install cmake packaging setuptools"
            CIBW_ARCHS_MACOS: "x86_64 arm64"
            CIBW_ARCHS_LINUX: "auto aarch64"
            CIBW_BUILD: "cp312-macosx_x86_64 cp312-macosx_arm64 cp312-win_amd64 cp312-manylinux_x86_64 cp312-musllinux_x86_64 cp312-manylinux_aarch64 cp312-musllinux_aarch64 cp313-macosx_x86_64 cp313-macosx_arm64 cp313-win_amd64 cp313-manylinux_x86_64 cp313-musllinux_x86_64 cp313-manylinux_aarch64 cp313-musllinux_aarch64"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install built wheel
        run: |
          pip install wheelhouse/*.whl
      - name: Run tests with unittest
        run: |
          python -m unittest bindings/python/test_python_bindings.py
      - if: matrix.os == 'ubuntu-22.04'
        name: Create stubs
        run: |
          python -m pip install wheel
          python ./tools/generate-stubs.py ./wheelhouse linux pybiginteger
      - name: Deploy
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Draft
          name: Draft
          draft: true
          files: |
            ./wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.deploy }}
